### ISSUE TITLE
Making header-only version of cupla

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/cupla#108]
As recently discussed offline and in emails, it would make sense to have an option to make cupla a header-only library, in addition to the current "normal" library. One use case is to simplify using it from build systems other than cmake.

Here is a link on [how some Boost libraries do this "optional header-only" configuration]( https://svn.boost.org/trac10/wiki/BestPracticeHandbook#a16.BUILD:Considerdefaultingtoheaderonlybutactivelymanagefacilitiesforreducingbuildtimes). It is essentially what we thought anyways, with a little more inlining.

**Comment by tdd11235813** [comment]
Ok, so this would be an addition/extension to PR #109 to provide an option for header-only configuration?

**Comment by sbastrakov** [comment]
Yes, we discussed it offline so of course @fwyzard could not have known about these considerations.

**Comment by fwyzard** [comment]
No problem, feel free to use this as a comparison point or baseline, or close it in favour of a better implementation.

**Comment by fwyzard** [comment]
No problem, feel free to use #109 as a comparison point, or close it in favour of a better implementation.

**Comment by psychocoderHPC** [comment]
implemented in #112
