### ISSUE TITLE
Lots of warnings with 0.4.0.

### ISSUE THREAD

**Issue by krzikalla** [ComputationalRadiationPhysics/cupla#119]
I get hundreds of warnings like this one:

../thirdparty/alpaka-develop/include/alpaka/vec/Vec.hpp(248): warning: __device__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration

Applies to __device__ and __host__ annotations.

Used cuda compiler flags
['-x=cu', '-ccbin', '/scratch/FSDM/rhel_7_6/fs_dependencies/gcc/bin/g++', '-m64', '-Xcompiler', '"-g","-fopenmp","-ggdb","-fPIC","-std=c++14"', '--expt-extended-lambda', '--expt-relaxed-constexpr', '--use_fast_math', '--ftz=false', '--generate-code', 'arch=compute_52,code=sm_52', '-std=c++14', '-DALPAKA_ACC_GPU_CUDA_ENABLED']

**Comment by psychocoderHPC** [comment]
I moved the issue to alpaka
