### ISSUE TITLE
Test minimal required CMake version

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/cupla#133]
Based on @ax3l's comment: https://github.com/ComputationalRadiationPhysics/cupla/pull/129#issuecomment-547191164
we should test in the CI the minimal required CMake version.

# Todo
- change CMake version in the CI back to 3.11.4
- update the minimal requirement for CMake in all cupla CMake scripts.

**Comment by sbastrakov** [comment]
Solved with #149.
