### ISSUE TITLE
Some atomic operations not defined

### ISSUE THREAD

**Issue by ivandrodri** [ComputationalRadiationPhysics/cupla#135]
I am writing a code with CUPLA and I need to use the atomicAnd, atomicOr and atomicXor bit operations. Is it possible to implement them in CUPLA or to somehow use the ALPAKA implementations?

Thanks!

**Comment by sbastrakov** [comment]
Thanks for keeping this in the loop @ax3l , I will do it.

**Comment by sbastrakov** [comment]
@ivandrodri thanks for your report, this is indeed a cupla shortcoming and it is possible to extend it slightly so that these operations are supported. Please expect it to be fixed this week.

**Comment by sbastrakov** [comment]
@ivandrodri this functionality is indeed missing in the `master` branch and the latest release. But, upon a further look, it was already added by #117 and so is available in the `dev` branch and will be part of the next release. In case you need it for the latest release, applying [the change](https://github.com/ComputationalRadiationPhysics/cupla/pull/117/files) manually should work: it's just inserting 3 new lines to a file.

**Comment by ivandrodri** [comment]
Thanks a lot!
