### ISSUE TITLE
Support for __float_as_int

### ISSUE THREAD

**Issue by mxmlnkn** [ComputationalRadiationPhysics/cupla#21]
and also for `__int_as_float`. I make use of it e.g. here

```
template<class T_FUNC>
__device__ inline void atomicFunc
(
    double * const rdpTarget,
    double const rValue,
    T_FUNC f
)
{
    using ull = unsigned long long int;
    ull assumed;
    ull old = * (ull*) rdpTarget;
    do
    {
        assumed = old;
        old = atomicCAS( (ull*) rdpTarget, assumed,
            __double_as_longlong( f( __longlong_as_double(assumed), rValue ) ) );
    }
    while ( assumed != old );
}
```

A host implementation could look like this: http://stackoverflow.com/a/13802260/2191065

**Comment by mxmlnkn** [comment]
This version is tested https://github.com/mxmlnkn/cupla/blob/d7b8482eaf813199ca10a12b6d833243610de254/include/cupla/cudaToCupla/driverTypes.hpp it had some problems before solved with https://github.com/mxmlnkn/cupla/commit/9b2baeddd15f9253c07d69ea7f9226de32588698 https://github.com/mxmlnkn/cupla/commit/9ed30c1fee611e27bd2985415ca482d2033f763a and https://github.com/mxmlnkn/cupla/commit/9b2baeddd15f9253c07d69ea7f9226de32588698
But currently it uses `ALPAKA_FN_NO_INLINE_HOST_ACC` meaning this needs to be adjusted to the result of https://github.com/ComputationalRadiationPhysics/alpaka/pull/194

**Comment by sbastrakov** [comment]
This is [implemented](https://github.com/ComputationalRadiationPhysics/cupla/blob/73fb269a8c080e613b0abe860f5d101ba1107e1d/include/cupla/cudaToCupla/driverTypes.hpp#L114-L119), closing.
