### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/cupla#79]
alpaka started to create a [logo](https://github.com/ComputationalRadiationPhysics/alpaka/issues/656). 
We need also a logo for cupla.

#draft 1

![cupla_final](https://user-images.githubusercontent.com/4037125/53403018-1b368d80-39b3-11e9-9965-211561fee9d3.png)

thx @steindev for your help

**Comment by theZiz** [comment]
I would make the left triangle orange, otherwise it looks like a bird of prey. Which isn't the worst thing as I just notice...

![cupla](https://user-images.githubusercontent.com/385145/46084872-f1c7ca80-c1a4-11e8-908d-5e430f90223d.gif)

**Comment by psychocoderHPC** [comment]
#draft 2
![cupla_2](https://user-images.githubusercontent.com/4037125/46085549-8da60600-c1a6-11e8-89a3-92eb6804feb3.png)

**Comment by theZiz** [comment]
I like the second draft more, but if you still want some more variety (colourwise) you may think about a blue upper or right triangle.

Regarding the font: It does not look very clingon, more playful. Clingons are not playful, but martial! You may try [this one](https://fonts.google.com/specimen/Pirata+One), but it may look more like Iron Sky than Clingons... [This one](https://fonts.google.com/specimen/Bahiana) may fit, too. Maybe [this](https://fonts.google.com/specimen/Kumar+One).

It's hard to find a font which does look martial, futuristic but not like federation p'tak...

**Comment by psychocoderHPC** [comment]
#draft 3
![cupla_4](https://user-images.githubusercontent.com/4037125/46086862-584ee780-c1a9-11e8-83e3-cf96c570c1ab.png)

**Comment by psychocoderHPC** [comment]
#draft 4
![cupla_3](https://user-images.githubusercontent.com/4037125/46087002-a9f77200-c1a9-11e8-9db6-e1a33bf8d780.png)

**Comment by theZiz** [comment]
Draft 3 hurts my eyes. Like draft 4. Any thoughts about the font?

**Comment by psychocoderHPC** [comment]
#draft 5

![cupla_4](https://user-images.githubusercontent.com/4037125/46145214-be964180-c25f-11e8-9670-532787f8a97e.png)

**Comment by theZiz** [comment]
The font is better, if you can't find something better, I would stay with this draft.

**Comment by ax3l** [comment]
I think draft one is the best. easy to read font and the blue edge looks fancy

**Comment by theZiz** [comment]
What has been seen can't be unseen.

**Comment by psychocoderHPC** [comment]
@ax3l used the [initial](https://github.com/ComputationalRadiationPhysics/cupla/issues/79#issue-364037384) logo already in a presentation so we will move this as the official logo.

**Comment by steindev** [comment]
Well, you could easily change to draft nr. 5 without anybody noticing. But one question remains to me. Wy don't you make the `C` of `Cupla` blue, like the rest of the font, and the left triangle orange. Then it would look like a bird. Which seems to be very cool to me, since the klingon battle ships are called `bird of prey`.

**Comment by psychocoderHPC** [comment]
@steindev 

![cupla_5](https://user-images.githubusercontent.com/4037125/51543947-16843400-1e5f-11e9-843c-12c68c05e36f.png)

We use the same colors in all our project so I am not sure if they should be different.

**Comment by tdd11235813** [comment]
I also would now use the initial logo for the poster.

**Comment by psychocoderHPC** [comment]
@tdd11235813 I will create a pull request soon but until for now here is the svg file of the logo version 1.
[cupla.svg.zip](https://github.com/ComputationalRadiationPhysics/cupla/files/2888893/cupla.svg.zip)

**Comment by sbastrakov** [comment]
Closed with #148.
