### ISSUE TITLE
Add cudaStreamQuery, cudaMemcpyToSymbol

### ISSUE THREAD

**Issue by tdd11235813** [ComputationalRadiationPhysics/cupla#82]
**cudaStreamQuery**

Use-case is a function that shows progress of a long-running kernel.
This involves querying the stream status. As long as stream is busy with kernel, it copies the counter value to host to display the progress (and waits a time before querying again).
(In our case we know the final value (100%), so we ~~stop polling then, although infinite loop might occur in buggy cases~~ can workaround cudaStreamQuery by just checking if 100% reached.)

**cudaMemcpyToSymbol**

Not implemented as well, a CUDA only solution would be:
```C++
cudaMemcpyToSymbol(/*...*/);
checkCudaErrors( cudaPeekAtLastError() );
```

Edit: I can add it to cupla, this issue just documents the request.

**Comment by psychocoderHPC** [comment]
`cudaStreamQuery` is now implemented in #85

**Comment by psychocoderHPC** [comment]
@tdd11235813 
`checkCudaErrors` is not a cuda function. It is a helper from the CUDA SDK. https://github.com/ComputationalRadiationPhysics/cupla/blob/master/example/CUDASamples/common/helper_cuda.h#L910

**Comment by psychocoderHPC** [comment]
`cudaPeekAtLastError` is implemented in #86

**Comment by tdd11235813** [comment]
thanks a lot for your PRs, just didn't have the time for it. Gonna try it out tomorrow :)

**Comment by tdd11235813** [comment]
Thanks again, our example works now, although I had to remove some other CUDA specific codes like constant or cuda includes.
