### ISSUE TITLE
types.hpp

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/cupla#9]
`cupla/types.hpp`
Maybe we want to change the naming of that file. nevertheless, be aware that if installed in a common prefix-directory (such as `/usr/include/cupla/`), naming collisions do not occur with other third party headers.

I would generally install our libraries only in prefixed dirs, see libSplash which is always inslide `splash/...` for users to include.

@psychocoderHPC 

Similar as in PMacc: https://github.com/ComputationalRadiationPhysics/picongpu/issues/1355

**Comment by psychocoderHPC** [comment]
`types.hpp` in `cupla` is already in a separate folder `cupla` therefore IMO there is no need to change the name. I will avoid a double branding of a file the the name of the folder where the file is located.

Could I close this issue?

**Comment by ax3l** [comment]
k!
